--- 
document: 
  description: |
    Questo documento descrive il processo di costruzione del modello di siti web
    per le scuole italiane. Definisce i criteri e le modalità di realizzazione e
    contiene tutti i riferimenti ai documenti più importanti relativi al
    progetto.    
  name: "Progetto siti web delle scuole"
  tags: 
    - siti web
    - design
    - scuole
